export const SET_ALL_REVENUES = 'SET_ALL_REVENUES';
export const SET_ALL_AVG_REVENUES = 'SET_ALL_AVG_REVENUES';
export const SET_NUMBER_CUSTOMERS = 'SET_NUMBER_CUSTOMERS';
export const SET_COUNTRIES = 'SET_COUNTRIES';
